### ISSUE TITLE
Track BATify extension growth

### ISSUE THREAD

**Issue by da2x** [BATgrowth/detect-bat-publishers#4]
[BATify](https://www.batify.net/) is a Brave Payments fork as a web browser extension.

You can track and plot the usage numbers for this third-party BAT client over time as a metric for BAT growth.

You can grab the number of daily active users (number of users who’ve checked for updates to these extensions) from these pages:

https://chrome.google.com/webstore/detail/batify/eamkmncdmlfaogagjpimecbmmkejbokd
https://addons.mozilla.org/en-US/firefox/addon/batify/

**Comment by kontrollanten** [comment]
Interesting! How reliable is BATify, it seems like a closed source project and I've never heard about it before?

**Comment by da2x** [comment]
> How reliable is BATify

No idea. It's a fork of the payment system in Brave (which is mostly an extension already). I only discovered it a few days ago. I have test payments going through in a few weeks.

> it seems like a closed source project 

https://github.com/mikel2000/batify

**Comment by fmarier** [comment]
The extension has been removed from both the Chrome and Firefox repositories.

**Comment by maxenceC** [comment]
@fmarier Thanks for the insight
