### ISSUE TITLE
Store historical stats

### ISSUE THREAD

**Issue by kontrollanten** [BATgrowth/detect-bat-publishers#5]
Since I couldn't find any repo for the website, https://batgrowth.com/publishers, I'll put the issue here. It would be really interesting to see historical stats at the site, then it'll be easier to see trends, etc.

**Comment by maxenceC** [comment]
I am already storing a "created_at" date after each crawling script to build an history

Number of results + date + array of results (urls), more exactly

It'll be available via batgrowth.com's API (which is not yet ready, but will be soon !)

**Comment by kontrollanten** [comment]
Positive news! Do you have any plans for putting the source for the API and website to GH?

**Comment by maxenceC** [comment]
>Do you have any plans for putting the source for the API and website to GH?

Yes, it's on my todo list, but i'm not sure when exactly I'll do it

**Comment by maxenceC** [comment]
@kontrollanten I've just added historical data charts for the number of publishers, for each platform (youtube, twitch, website) on the main page : https://batgrowth.com
