### ISSUE TITLE
Numbers are hard

### ISSUE THREAD

**Issue by da2x** [BATgrowth/detect-bat-publishers#6]
“there are 896 detected Brave/BAT publishers amongst Alexa's Top 1M websites”

“Showing 1 to 300 of 592 entries”

Either it’s 592 or its 896 websites.

**Comment by maxenceC** [comment]
Websites that haven't been proccessed in the cron to gather their alexa
rank aren't displayed yet in the table

I need to explain this somewhere

Thanks for the insight

**Comment by marktolson** [comment]
This is still wrong: 

"As of today, there are 5324 detected Brave/BAT publishers amongst Alexa's Top 1M websites, that's 0.5324%"

According to the table there are less than 900 sites in the top 1 million. Most are in the 1 million-10 million rankings. The sentence should be:

"As of today, there are 5324 detected Brave/BAT publishers amongst Alexa's Top **10M** websites, that's **0.05324%**"

**Comment by maxenceC** [comment]
This was fixed in the last release
